
                                                                  -- DAY FOUR TASKS-2 --

-- 1. CREATE A DATABASE NAMED COLLEGE_DB AND SWITCH TO IT.
DROP DATABASE COLLEGE_DB;
CREATE DATABASE COLLEGE_DB;

USE COLLEGE_DB;

SHOW DATABASES;
-- 2. CREATE A TABLE TEACHERS WITH COLUMNS: TEACHER_ID, NAME, SUBJECT, AND PHONE.
-- 3. SET TEACHER_ID AS THE PRIMARY KEY AND AUTO_INCREMENT.
-- 4. SET PHONE TO BE UNIQUE IN THE TEACHERS TABLE.

CREATE TABLE TEACHERS(TEACHER_ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(25), SUBJECT VARCHAR(25), 
PHONE CHAR(10) UNIQUE);

DESCRIBE TEACHERS;

-- 5. CREATE A TABLE COURSES WITH A FOREIGN KEY REFERENCING TEACHER_ID FROM TEACHERS.

CREATE TABLE COURSES(ROLL_NO INT, FOREIGN KEY (ROLL_NO) REFERENCES TEACHERS(TEACHER_ID));
ALTER TABLE COURSES ADD COLUMN PERIOD CHAR(3);
--
-- CREATE TABLE MARKS(REG_NO INT,FOREIGN KEY (REG_NO) REFERENCES STUDENTS(ROLL_NO),SUBJECT VARCHAR(25), MARKS FLOAT ,GRADE CHAR(1));
-- INSERT INTO MARKS VALUES(3,"PYTHON",8,"A");
--

-- 6. CREATE A TABLE STUDENTS WITH FIELDS INCLUDING NAME, ROLL_NO, DOB, PHONE_NUMBER, GENDER, AND COURSE.
CREATE TABLE STUDENTS(ROLL_NO INT, DOB DATE, PHONE_NUMBER CHAR(10) UNIQUE, 
GENDER CHAR(1) CHECK (GENDER IN ("M", "F", "O")) DEFAULT "M", COURSE VARCHAR(25) 
CHECK(COURSE IN ("DS", "AS", "MS", "AI")));

-- 7. INSERT 3 RECORDS INTO THE TEACHERS TABLE.

INSERT INTO TEACHERS(TEACHER_ID, NAME, SUBJECT, PHONE) 
VALUES(001, "SAM", "CHEMISTRY", "9865321470"); -- 1ST RECORD

INSERT INTO TEACHERS(NAME, SUBJECT, PHONE) 
VALUES("RAJ", "PHYSICS", "69853265"); -- 2ND RECORD

INSERT INTO TEACHERS(NAME, SUBJECT, PHONE) 
VALUES("RAM", "PWRBI", "1236547890"); -- 3RD RECORD

DESC TEACHERS;

SELECT * 
FROM TEACHERS;

-- 8. INSERT 3 RECORDS INTO THE COURSES TABLE LINKED TO TEACHERS.
INSERT INTO COURSES VALUES (1, "1ST"); -- 1ST RECORD

INSERT INTO COURSES VALUES (2, "2ND"); -- 2ND RECORD

INSERT INTO COURSES VALUES (3, "3RD"); -- 3RD RECORD 

SELECT * 
FROM COURSES;

 -- 9. INSERT A STUDENT RECORD WITH ALL FIELDS FILLED.

INSERT INTO STUDENTS (ROLL_NO, DOB, PHONE_NUMBER, GENDER, COURSE) 
VALUES (1, "2020-05-05", "856321478", "M", "AS");

 -- 10. INSERT A STUDENT RECORD WITHOUT SPECIFYING THE GENDER (SHOULD USE DEFAULT VALUE).
 
 INSERT INTO STUDENTS (ROLL_NO, DOB, PHONE_NUMBER, COURSE) VALUES (2, "2020-03-03", "356321478", "DS");
 
 SELECT * 
FROM STUDENTS;
