-- JOINS

USE HR;

SELECT *
FROM EMPLOYEES;


SELECT *
FROM DEPARTMENTS;

SELECT EMPLOYEES.EMPLOYEE_ID, DEPARTMENTS.DEPARTMENT_NAME, DEPARTMENTS.DEPARTMENT_ID
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEE_ID, DEPARTMENT_NAME,A.DEPARTMENT_ID
FROM EMPLOYEES AS E
LEFT JOIN DEPARTMENTS AS A
ON E.DEPARTMENT_ID=A.DEPARTMENT_ID;

SELECT EMPLOYEE_ID, DEPARTMENT_NAME, EMPLOYEES.DEPARTMENT_ID,DEPARTMENTS.DEPARTMENT_ID, LOCATION_ID
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS ON 
EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
ORDER BY DEPARTMENT_NAME;

-- SELF JOIN

SELECT *
FROM EMPLOYEES AS E
JOIN EMPLOYEES AS M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

SELECT E.FIRST_NAME, M.FIRST_NAME
FROM EMPLOYEES AS E
JOIN EMPLOYEES AS M
ON E.MANAGER_ID = M.EMPLOYEE_ID;
